# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'permissions': [('es_administrador', 'es administrador')]},
        ),
    ]
