# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuario.Usuario')),
                ('genero', models.CharField(max_length=9)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('direccion', models.TextField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo solo admite letras.', regex='^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')])),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=50)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Pago')),
            ],
            options={
                'ordering': ['-fecha'],
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='ProductoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('total', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Producto')),
            ],
            options={
                'ordering': ['pedido'],
                'db_table': 'productos_pedidos',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Departamento'),
        ),
    ]
