# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('ver_perfil', 'puede ver su perfil')]},
        ),
    ]
