# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20170218_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
    ]
