# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_pago_pedido_productopedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productopedido',
            options={'ordering': ['pedido']},
        ),
        migrations.AlterModelTable(
            name='productopedido',
            table='productos_pedidos',
        ),
    ]
