# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20170215_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(error_messages={'blank': '\xbfC\xfaal es el nombre del Departamento?', 'max_length': 'El n\xfamero de caracteres no es v\xe1lido.'}, max_length=30),
        ),
    ]
