# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20170218_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('see_profile', 'ver perfil')]},
        ),
    ]
