# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20170218_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('es_cliente', 'es cliente')]},
        ),
    ]
