# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20170216_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
