# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_auto_20170216_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se admiten letras.', regex='^[A-Za-z\xe1\xe9\xed\xf3\xfa\xc1\xc9\xcd\xd3\xda\\s]+$')]),
        ),
    ]
